# Generated by Django 2.2.6 on 2019-10-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20191023_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='date',
            field=models.DateTimeField(default='1970-01-01 00:00'),
        ),
    ]
