# -*- coding: utf-8 -*-
"""
Created on Fri Feb 15 09:03:17 2019

@author: gvega
"""

import pyautogui
import time

pyautogui.position()
pyautogui.moveTo([405,337], duration = .25)
pyautogui.click(duration = .25)
for row in range(66,126):
    print(row)
    
    #pyautogui.moveTo([405,337], duration = .25)
    #pyautogui.click(duration = .25)
    pyautogui.press('down')
    time.sleep(0.5)  
    pyautogui.press('alt')      
    time.sleep(0.2)  
    pyautogui.press('b')
    time.sleep(0.2) 
    pyautogui.press('z')
    pyautogui.press('i')
    time.sleep(0.2) 
    pyautogui.press('i')
    pyautogui.press('m')
    
    pyautogui.moveTo([236,164], duration = .25)
    time.sleep(0.5)
    pyautogui.click(duration = .25)
    time.sleep(1)
    
    for n in range(1,row):
        pyautogui.press('right')
        time.sleep(0.3)
        
    
    pyautogui.press('enter')
    time.sleep(1)
    pyautogui.press('alt')
    time.sleep(0.8)
    pyautogui.press('J')
    time.sleep(0.8)
    pyautogui.press('P')
    time.sleep(0.8)
    pyautogui.press('L')
    time.sleep(0.8)
    pyautogui.press('L')
    time.sleep(0.8)
    pyautogui.press('2')
    time.sleep(0.8)
    pyautogui.press('enter')   
    time.sleep(0.8)
    pyautogui.keyDown('shift')
    time.sleep(0.8)
    pyautogui.press('f10')  
    time.sleep(0.8)
    pyautogui.keyUp('shift')
    time.sleep(0.8)
    pyautogui.press('up')   
    time.sleep(0.8)
    pyautogui.press('enter')
    time.sleep(0.8)
    pyautogui.moveTo([627,268], duration = .25)
    time.sleep(0.5)
    pyautogui.click(duration = .25)    
    pyautogui.moveTo([585,365], duration = .25)
    time.sleep(0.5)
    pyautogui.click(duration = .25)      
    time.sleep(0.5)
    pyautogui.moveTo([776,229], duration = .25)
    time.sleep(0.5)
    pyautogui.click(duration = .25)   
    time.sleep(0.5)
    pyautogui.press('esc')    
    time.sleep(0.5)
    pyautogui.keyDown('shift')
    time.sleep(0.5)
    pyautogui.press('f10')  
    time.sleep(0.5)
    pyautogui.keyUp('shift')  
    time.sleep(0.5)
    pyautogui.press('up')   
    time.sleep(0.5)
    pyautogui.press('up')   
    time.sleep(0.5)
    pyautogui.press('up')   
    time.sleep(0.5)
    pyautogui.press('up')   
    time.sleep(0.5)
    pyautogui.press('up')   
    time.sleep(0.5)
    pyautogui.press('enter')   
    time.sleep(0.5)  
    pyautogui.press('esc')   
    time.sleep(0.5)       
    pyautogui.keyDown('shift')
    time.sleep(0.5)
    pyautogui.press('f10')  
    time.sleep(0.5)
    pyautogui.keyUp('shift')      
    time.sleep(0.5)
    pyautogui.press('up')      
    time.sleep(0.5)
    pyautogui.press('up')      
    time.sleep(0.5)
    pyautogui.press('up')      
    time.sleep(0.5)
    pyautogui.press('enter')   
    time.sleep(0.5)   
    if row == 2:
        time.sleep(0.5)    
        pyautogui.press('right')      
        time.sleep(0.5)
        pyautogui.press('right')          
        time.sleep(0.5)   

    pyautogui.press('tab')      
    time.sleep(1)   
    pyautogui.press('enter')      
    time.sleep(2)      
    pyautogui.moveTo([312,458], duration = .25)
    time.sleep(2)
    pyautogui.click(duration = .25)      
    time.sleep(2)
    pyautogui.press('right')      
    time.sleep(1)
    pyautogui.press('right') 
    time.sleep(1)
    pyautogui.press('right')      
    time.sleep(1)      
    pyautogui.moveTo([364,354], duration = .25)
    pyautogui.click(duration = .25)         
    time.sleep(1)    
    pyautogui.moveTo([217,197], duration = .25)
    pyautogui.click(duration = .25)         
    time.sleep(1)    
    #pyautogui.press('left') 
    #time.sleep(0.5)
    #pyautogui.press('left') 
    #time.sleep(0.5)
    pyautogui.moveTo([388,269], duration = .25)
    pyautogui.click(duration = .25)         
    time.sleep(1)        

    for n in range(1,row):
        time.sleep(0.8)
        pyautogui.press('right')
        time.sleep(0.8) 
    
    time.sleep(0.8)
    pyautogui.press('enter')      
    time.sleep(0.8)
    pyautogui.press('enter')     
    time.sleep(0.8)    
    pyautogui.moveTo([439,492], duration = .25)
    pyautogui.click(duration = .25)  
    pyautogui.press('esc')