# Generated by Django 2.2.6 on 2019-10-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('revenue', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
