# Generated by Django 2.2.6 on 2019-10-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_aapl_hpq_msft_sne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
