# Generated by Django 2.2.6 on 2019-10-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_currencies_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='date',
            field=models.DateTimeField(default='1970.01.01 00:00'),
        ),
    ]
