# Generated by Django 2.2.6 on 2019-10-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20191023_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='date',
            field=models.CharField(max_length=22),
        ),
    ]
