# Generated by Django 2.2.6 on 2019-10-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20191023_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='MovingAverage',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=6),
        ),
    ]
