# Generated by Django 2.2.6 on 2019-11-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_emailsignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='Close',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='High',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='Low',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='MovingAverage',
            field=models.DecimalField(decimal_places=6, default='0', max_digits=30),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='Open',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='Volume',
            field=models.DecimalField(decimal_places=1, max_digits=30),
        ),
    ]
